"""Thematic eligibility notes (M output) and key risks for every v4 holding. Team-written from company reports; dated targets
are supporting evidence only (no longer an eligibility test). cap = capacity provided; moat = why it is hard to replace;
earn = how the company earns from it; risk = main competitive, regulatory or financial risk; ev = supporting evidence (optional)."""
STORY = {'Power generation & grids': 'First home: the power behind the electricity bill',
         'Water': 'First home: a reliable water connection',
         'Digital networks': 'First job: the network behind every phone, laptop and payment',
         'Ports': 'First business: goods coming in and going out',
         'Airports & toll roads': 'First trip: the airport and the road to it',
         'Healthcare facilities': 'First family: the hospital beds and specialists a family relies on',
         'Grid & power equipment': 'First home: the transformers and cables that connect it',
         'Semiconductors': 'Every first: the chips inside phones, laptops and data centres'}
N = {
 'EXC': dict(cap='Regulated electricity and gas delivery networks in Chicago, Philadelphia, Baltimore and Washington DC (ComEd, PECO, BGE, Pepco)',
             moat='State-franchised monopoly networks; no competing wires can be built', earn='Regulated return on a growing rate base',
             risk='Rate-case outcomes; highest leverage of the power holdings (6.1× net debt/EBITDA)'),
 'WPRTS': dict(cap='Container terminals at Port Klang, Malaysia, on the Strait of Malacca', moat='Long-dated government concession and deep-water berths on a scarce site',
               earn='Per-container handling tariffs', risk='Tariff approvals and execution of the Westports 2 expansion',
               ev=('Capacity from 14M to 27M TEU a year (Westports 2)', 'https://theedgemalaysia.com/node/773945')),
 'ICT': dict(cap='Global container-port operator; home base Manila International Container Terminal', moat='Multi-decade port concessions; MICT renewed for another 25 years in 2026',
             earn='Handling fees under long concessions in emerging markets', risk='Emerging-market concession, currency and political risk',
             ev=('US$300M to expand MICT, South Luzon and Mindanao terminals by 2028', 'https://context.ph/2026/07/30/ictsi-secures-mict-operations-for-another-25-years/')),
 'ENGI': dict(cap='French gas and power networks plus renewable and thermal generation', moat='Regulated network concessions; licensed generation sites',
              earn='Regulated network returns plus contracted and merchant power', risk='Power prices; French state influence over tariffs',
              ev=('95 GW of renewables and storage by 2030 (57.2 GW end-2025)', 'https://www.engie.com/app/uploads/2026/03/PR-ENGIE-FY-2025-VDEF.pdf')),
 'BDMS': dict(cap="Thailand's largest private hospital network", moat='Hospital licences, specialist staff and referral networks built over decades',
              earn='Patient fees from insured, self-pay and international patients', risk='Medical-tourism demand; Thai economy and staff costs'),
 'EOAN': dict(cap="Electricity distribution grids in Germany and across Europe, one of the continent's largest", moat='Regulated distribution concessions',
              earn='Regulated return on grid investment', risk='German regulator resets allowed returns; heavy capex to fund'),
 'SULAIMAN': dict(cap="Saudi Arabia's largest private hospital group", moat='Licensed hospitals and scarce specialist workforce',
                  earn='Fees from insurers and government contracts', risk='Valuation above healthcare peers (24.9× vs 17.2× median); Saudi reimbursement policy'),
 'GDI': dict(cap="Dongshen bulk-water scheme supplying most of Hong Kong's fresh water, plus Guangdong water networks", moat='The only bulk link of its kind; supply agreement with the Hong Kong government',
             earn='Contracted water-supply fees', risk='State-owned group with property exposure; renegotiation of the Hong Kong water price'),
 'KDDI': dict(cap="Japan's second-largest mobile and fibre network (au)", moat='Spectrum licences and nationwide network', earn='Subscription revenue',
              risk='Government pressure on mobile tariffs; competition'),
 'EHC': dict(cap='Largest US operator of inpatient rehabilitation hospitals', moat='Certificate-of-need rules in many states; Medicare-certified facilities',
             earn='Mostly Medicare reimbursement per patient stay', risk='Medicare rate changes'),
 'T': dict(cap='US nationwide wireless and fibre network', moat='Spectrum licences and fibre that takes years to replicate', earn='Subscription revenue',
           risk='Leverage (3.3×) and heavy network capex'),
 'MOUWASAT': dict(cap='Private hospitals in Saudi Arabia (Eastern Province, Riyadh)', moat='Hospital licences and specialist staff',
                  earn='Patient fees from insurers', risk='Small listing and thin trading, though its weight is well inside its liquidity limit'),
 'CHTEL': dict(cap="China's fibre-broadband and mobile network, plus cloud data centres", moat='State telecom licence; national fibre network',
               earn='Subscription and cloud revenue', risk='State control; US sanctions history (delisted from NYSE in 2021)'),
 'SBS': dict(cap='Water and sewage for São Paulo state', moat='Municipal concession; regulated monopoly network', earn='Regulated tariffs',
             risk='Large capex plan keeps free cash flow negative; Brazilian real',
             ev=('About R$70bn of works to universalise water and sewage by 2029', 'https://www.infomoney.com.br/mercados/sabesp-supera-metas-de-novas-ligacoes-e-reforca-plano-de-universalizar-ate-2029/')),
 'CHMOB': dict(cap="World's largest mobile network by subscribers, plus AI computing", moat='State licences; spectrum', earn='Subscription and computing revenue',
               risk='State control; sanctions exposure',
               ev=('100 EFLOPS of AI computing power by 2028', 'https://www.scmp.com/business/article/3328842/china-mobile-aims-triple-ai-computing-power-using-homegrown-chips-2028')),
 'HCA': dict(cap='Largest US hospital operator', moat='Certificate-of-need laws and local scale in its markets', earn='Patient revenue from insurers, Medicare and Medicaid',
             risk='US health policy (Medicaid funding); leverage 3.2×'),
 'ENEL': dict(cap="Italy's main electricity distribution grid plus renewables in Europe and Latin America", moat='Regulated grid concessions',
              earn='Regulated returns plus generation', risk='Regulation and Latin American exposure; controls Endesa (watchlist, P4)',
              ev=('Installed capacity from ~68 GW to over 80 GW by 2028', 'https://www.teleborsa.it/AMP/News/2026/02/23/enel-il-50percent-dei-capex-per-rinnovabili-e-in-europa-capacita-installata-salira-a-80-gw-17.html')),
 'STC': dict(cap="Saudi Arabia's main telecom network and data centres (center3)", moat='Licences, spectrum and the national backbone', earn='Subscription and data-centre revenue',
             risk='State ownership; one-country concentration',
             ev=('center3 targets 1 GW of data-centre capacity by 2030', 'https://www.datacenterdynamics.com/en/news/saudis-center3-targets-1gw-of-data-center-capacity-by-2030/')),
 'AIRTEL': dict(cap="India's second-largest mobile network, plus Africa", moat='Spectrum and nationwide towers and fibre', earn='Subscription revenue',
                risk='Indian regulation and the rupee',
                ev=('Nxtra data-centre capacity doubled to 400 MW by 2026', 'https://w.media/nxtra-planning-200-mw-data-center-in-hyderabad/')),
 'DTE': dict(cap="Germany's largest telecom network; majority owner of T-Mobile US", moat='Spectrum and fibre', earn='Subscription revenue',
             risk='Leverage (3.3×); overlaps US telecom exposure through T-Mobile US',
             ev=('Fibre to every household and business in Germany by 2030', 'https://report.telekom.com/annual-report-2024/management-report/group-strategy/investments.html')),
 'BH': dict(cap='International hospital in Bangkok, a regional medical-tourism hub', moat='Specialist staff, accreditation and international referral base',
            earn='Patient fees, a large share from foreign patients', risk='Dependence on medical tourism (Middle East, Asia)'),
 'QCOM': dict(cap='Wireless modem and processor chips plus standard-essential patents for mobile networks', moat='Patent portfolio embedded in 4G/5G standards; design scale',
              earn='Chip sales and patent licensing', risk='Losing Apple modem business; China exposure; cycle'),
 'AMX': dict(cap="Latin America's largest telecom network (Telcel, Claro)", moat="Spectrum and the region's largest fibre network", earn='Subscription revenue',
             risk='Mexican regulation and Latin American currencies',
             ev=('Over 5,400 km of new fibre in Peru during 2026', 'https://www.claro.com.pe/portal/pe/recursos_contenido/pdf/NP_Proyeccion_Despliegue-FO2026-140826.pdf')),
 'OMAB': dict(cap='13 airports in north-central Mexico, including Monterrey', moat='Government concessions; airports cannot be duplicated nearby',
              earn='Regulated passenger charges plus commercial income', risk='Air traffic shocks (60% EBITDA stress still passes); peso',
              ev=('MXN 16bn 2026-30 plan; Monterrey capacity up ~50% to over 18M passengers', 'https://www.elfinanciero.com.mx/empresas/2026/06/05/oma-destina-16-mil-mdp-a-tecnologia-y-expansion-de-sus-aeropuertos/')),
 'ADVANTEST': dict(cap='Test equipment that every advanced chip must pass before shipping', moat='Leading share of system-on-chip testers; years of customer qualification',
                   earn='Equipment and service sales', risk='Cycle and valuation (50× EV/EBITDA against a 35.9× semiconductor median)'),
 'HDHE': dict(cap='Power transformers and switchgear for grids and data centres', moat='Transformer factories take years to build and qualify; long order backlog',
              earn='Equipment sales from a multi-year backlog', risk='Orders at a cyclical high',
              ev=('KRW 397bn to expand Ulsan and Alabama transformer capacity by 2028', 'https://transformer-magazine.com/news/hd-hyundai-electric-to-invest-272-3-m-in-transformer-production/')),
 'NVDA': dict(cap='AI accelerator chips and data-centre networking', moat='CUDA software ecosystem and design scale competitors have not matched',
              earn='Hardware and systems sales to cloud and enterprise data centres', risk='Customer concentration; export controls; AI capex cycle'),
 'VST': dict(cap='US power generation fleet (gas and nuclear) and retail electricity in Texas', moat='Licensed plants, including nuclear, that take a decade to replace',
             earn='Power sales, part contracted', risk='Wholesale power prices; leverage 3.0×'),
 'SKHYNIX': dict(cap='DRAM and high-bandwidth memory (HBM) for AI', moat='Few firms can make leading-edge memory; HBM qualification with AI chipmakers',
                 earn='Memory sales', risk='Memory cycle at a peak',
                 ev=('KRW 19tn Cheongju HBM packaging fab by end-2027', 'https://www.trendforce.com/news/2026/01/13/news-sk-hynix-to-build-cheongju-advanced-packaging-fab-boosting-hbm-output-by-2027/')),
 'MU': dict(cap='DRAM, high-bandwidth memory and NAND', moat='One of three leading-edge DRAM makers worldwide', earn='Memory sales', risk='Memory cycle at a peak',
            ev=('Idaho DRAM fab output from 2027', 'https://www.trendforce.com/news/2025/06/13/news-micron-to-invest-200b-in-u-s-amid-trumps-reshoring-drive-targeting-40-dram-made-in-america/')),
 'ENR': dict(cap='Gas turbines, grid technology (transformers, HVDC links) and wind turbines', moat='One of a handful of makers of large turbines and HVDC systems',
             earn='Equipment and long-term service contracts', risk='Wind-turbine losses and execution'),
}
